rbac:
  enabled: true

ingress:
  enabled: true

serviceType: ClusterIP

environment: testing

user:
  password: root


postgresql:
  enabled: false

externalServices:
  postgresql:
    user: polyaxon
    password: polyaxon
    database: postgres
    host: 35.226.163.84
    port: 1111
